name: pr_comment_trigger

on:
  issue_comment:
    types: [created, edited]

jobs:
  your_job:
    if: github.event.issue.pull_request != null && startsWith(github.event.comment.body, 'upload')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered!"
      - name: Add PR comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMENT_BODY="👋 This is a GitHub Action comment!"
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"body\": \"$COMMENT_BODY\"}" \
               "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments"
