name: pr_comment_trigger

on:
  issue_comment:
    types: [created, edited]

jobs:
  your_job:
    if: github.event.issue.pull_request != null && startsWith(github.event.comment.body, 'upload')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered!"