name: pr_comment_trigger

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write  # Needed to comment on issues/PRs

jobs:
  your_job:
    if: github.event.issue.pull_request != null && startsWith(github.event.comment.body, 'upload')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered!"
      - name: Comment on the PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          COMMENT_BODY="👋 This is a GitHub Action comment!"
          API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments"
      
          echo "🔍 Will POST to: $API_URL"
          echo "📦 Payload: {\"body\": \"${COMMENT_BODY}\"}"
      
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
               -H "Content-Type: application/json" \
               -d "{\"body\": \"${COMMENT_BODY}\"}" \
               "$API_URL"

